# Generated by Django 4.2.7 on 2025-08-19 20:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="design",
            name="slug",
        ),
    ]
